# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b30daad3ae2c2643c537333d8593ab7552d16114c1fd5e1cc86ee4cdf9609e84aa5d03470c57164de9de1fe1296aecbecdbeee30c4155cc7093496d5bac9f2b5

test:
  secret_key_base: b827f8d2e7d8bf87d22c483787d055f70923d30758341d1e91a2ed3341e31b7f51e2e86ea56b04391b88723a0664501d385bde6ff5b293612465b34ed4b038d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
